id: 0f11b031365545dcabba7382f231d600
initial_creation_type: ocr
source_metadata:
  volumes:
    f998a1e675944dfbb88d55c8705cc30a:
      base_file: v011.txt
      image_group_id: I1PD95856
      title: ''
      total_pages: 2107
      volume_number: 11
